# from: https://github.com/packit/packit/blob/main/.github/workflows/prepare-release.yml
name: Prepare a new release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version number for the new release
      branch:
        required: true
        description: Branch to release from

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Update translations from weblate
        if: ${{ inputs.branch == 'main' }}
        uses: ./.github/actions/weblate-pull-translations

      - name: Prepare release content
        uses: rpm-software-management/prepare-release-dnf5@d39d17f1db15fffb9382ce045e98243b9a856eaf
        with:
          version: ${{ inputs.version }}
          specfiles: dnf5.spec

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          labels: release
          commit-message: Release ${{ inputs.version }}
          title: Release ${{ inputs.version }}
          body: Update the changelog and the specfile for release ${{ inputs.version }}.
          base: ${{ inputs.branch }}
          branch-suffix: short-commit-hash
          delete-branch: true
